language: python
sudo: false
python:
- '2.7'
install:
- pip install flake8
script: flake8 .
before_deploy: echo ${TRAVIS_TAG} > VERSION
deploy:
  provider: pypi
  skip_cleanup: true
  on:
    tags: true
  user: vandmo
  password:
    secure: ON1d2hkqB5H5z6+XiNNUqSYe908dPskQYcbQQXCSaKTq8RpcFPhA3lVr34kMul09zOpDk/xY243uAFuu40oAzcHlqKAC+Q+PjRTNvXoOXEdI16TmyPB15Vp0gEjD8OnBn8CD19VhPl5KC5EbPKnHJW/Te0egHCowk2kAxV7J7MMP3wNATGjKt/eFTLIKTkQ/L7nwlmrDRVz3YwBnTpLz4z1rn5VXEnvgu3jRBbuFh857Q5nbwLnJVSR2jzcGDfvRaZ2aVk3OUpReOSzY1poEe7r/XD4eZVWAviNKiOAKwWB+1PN7IUD73UNzfYzwhROTBjXbYezHP3/K3WWNAlLjxUoPKHTHmmZ1a5muui8Iofxvb55jWLOKaRquUjQex1Xd8aOdq1k6pwQxUFP9K/TNI8EupAndnsKLxeB0ojgbO2DaYFF6dqehS8wP+/m/NN8qjuc0iCUHkOOSA0cm6KZJo9wElgW2cXX9aVte2hDbnmIiD3v2+BQr5CdqWRfRB0V08i6HKLtmS8hIGurrjKy5jwShZCeKRD4QedpcMm94k9jyImUrlKNoUTcQSPgh95lnnu8OG7zOQF9Ut7oX75asXp3eiR4u6FkmW+ecB/qRzB2aNB8oF6lKfxEfs4MFaySeYFjfaRHek8saqag4O6PdBAjIsfIQAZymklWJKS0C/78=
